import '@fa-pro-svg/light/arrow-right.svg'
import '@fa-pro-svg/light/tachometer-alt-fast.svg'
import '@fa-pro-svg/light/list-ul.svg'
import '@fa-pro-svg/light/stars.svg'
import '@fa-pro-svg/light/cog.svg'
import '@fa-pro-svg/light/sync.svg'

import '@fa-pro-svg/regular/external-link.svg'
import '@fa-pro-svg/regular/arrow-right.svg'
import '@fa-pro-svg/regular/arrow-left.svg'
import '@fa-pro-svg/solid/caret-right.svg'
import '@fa-pro-svg/solid/caret-left.svg'
import '@fa-pro-svg/regular/check-square.svg'
import '@fa-pro-svg/regular/times.svg'
import '@fa-pro-svg/regular/check.svg'
import '@fa-pro-svg/regular/store-alt.svg'
import '@fa-pro-svg/regular/user-alt.svg'
